//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Editor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberBasketBanana
    {
        public string Email { get; set; }
        public int BananaId { get; set; }
        public int Quantity { get; set; }
    
        public virtual Banana Banana { get; set; }
        public virtual MemberBasket MemberBasket { get; set; }
    }
}
