//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Editor.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StoresEntities : DbContext
    {
        public StoresEntities()
            : base("name=StoresEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Apple> Apples { get; set; }
        public virtual DbSet<Banana> Bananas { get; set; }
        public virtual DbSet<MemberBasketApple> MemberBasketApples { get; set; }
        public virtual DbSet<MemberBasketBanana> MemberBasketBananas { get; set; }
        public virtual DbSet<MemberBasket> MemberBaskets { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
